import { useEffect, useRef, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Code2, Copy, ExternalLink, Github, Mail, Menu, MessageCircle, X } from 'lucide-react'
import { otherProjects, projects, type Project } from './data/projects'

const nav = [['sobre','Sobre'],['projetos','Projetos'],['processo','Processo'],['competencias','Competências'],['formacao','Formação']]
const process = ['Compreender','Pesquisar','Planejar','Prototipar','Desenvolver','Testar','Melhorar']
const skills = [
  {title:'Front-end', note:'Prática em projetos', items:['HTML','CSS','JavaScript','TypeScript','React','SASS','Responsividade']},
  {title:'Back-end e programação', note:'Prática e estudos', items:['Node.js','PHP','Java','APIs','MySQL','SQLite','Testes']},
  {title:'UX e qualidade', note:'Foco de trabalho', items:['UX Design','UI Design','Prototipação','Acessibilidade','Quality Assurance','Plano de testes']},
  {title:'Ferramentas e métodos', note:'Uso e estudos', items:['Git','GitHub','Codex','Claude Code','Engenharia de Prompt','IA generativa','n8n','Google Cloud']},
]

function Header(){
  const [open,setOpen]=useState(false); const [active,setActive]=useState('sobre')
  useEffect(()=>{const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-25% 0px -65%'});nav.forEach(([id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[])
  return <header className="site-header"><a className="monogram" href="#inicio" aria-label="Inicio - Luiz Moutinho">LM</a><button className="icon-button menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="main-nav" aria-label={open?'Fechar menu':'Abrir menu'}>{open?<X/>:<Menu/>}</button><nav id="main-nav" className={open?'nav open':'nav'} aria-label="Navegacao principal">{nav.map(([id,label])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}<a className="button button-small" href="#contato" onClick={()=>setOpen(false)}>Vamos conversar</a></nav></header>
}

function ProjectCard({project,onOpen}:{project:Project,onOpen:(p:Project)=>void}){
  const imageUrl = project.image ? `${import.meta.env.BASE_URL}${project.image.replace(/^\//, '')}` : undefined
  return <article className="project-card">{imageUrl?<img src={imageUrl} alt={project.imageAlt} loading="lazy"/>:<div className={`project-art art-${project.id}`} role="img" aria-label={`Preview ilustrativo do projeto ${project.name}`}><span>{project.eyebrow}</span><strong>{project.name.slice(0,2).toUpperCase()}</strong><small>preview ilustrativo</small></div>}<div className="project-body"><div className="project-meta"><span>{project.category}</span><span>{project.status.split(';')[0]}</span></div><h3>{project.name}</h3><p>{project.summary}</p><ul className="tags" aria-label="Tecnologias">{project.technologies.slice(0,4).map(t=><li key={t}>{t}</li>)}</ul><div className="card-actions"><button className="text-link" onClick={()=>onOpen(project)}>Ver estudo de caso <ArrowRight/></button>{project.repo&&<a className="icon-link" href={project.repo} target="_blank" rel="noreferrer" aria-label={`Repositório de ${project.name}`}><Github/></a>}</div></div></article>
}

function CaseDialog({project,onClose}:{project:Project,onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null); useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close()},[])
  return <dialog ref={ref} className="case-dialog" onClose={onClose} onClick={e=>{if(e.target===ref.current)ref.current.close()}}><div className="dialog-head"><div><span className="kicker">{project.eyebrow}</span><h2>{project.name}</h2></div><button className="icon-button" onClick={()=>ref.current?.close()} aria-label="Fechar estudo de caso"><X/></button></div><p className="dialog-lead">{project.summary}</p><div className="case-grid"><section><h3>Necessidade</h3><p>{project.problem}</p></section><section><h3>Solucao</h3><p>{project.solution}</p></section>{project.role&&<section><h3>Meu papel</h3><p>{project.role}</p></section>}<section><h3>Status</h3><p>{project.status}</p></section></div><section><h3>Principais funcionalidades</h3><ul className="check-list">{project.features.map(x=><li key={x}><Check/>{x}</li>)}</ul></section><section><h3>Decisoes de design e UX</h3>{project.decisions.map(x=><p key={x}>{x}</p>)}</section>{project.challenges&&<section><h3>Desafio tecnico</h3><p>{project.challenges}</p></section>}{project.learnings&&<section><h3>Aprendizado</h3><p>{project.learnings}</p></section>}<ul className="tags">{project.technologies.map(t=><li key={t}>{t}</li>)}</ul>{project.repo&&<a className="button" href={project.repo} target="_blank" rel="noreferrer"><Github/> Ver codigo <ExternalLink/></a>}</dialog>
}

export default function App(){
  const [selected,setSelected]=useState<Project|null>(null); const [copied,setCopied]=useState(false)
  const copyEmail=async()=>{await navigator.clipboard.writeText('luizmariomoutinho1@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),1800)}
  return <><a className="skip-link" href="#conteudo">Pular para o conteudo</a><Header/><main id="conteudo">
    <section id="inicio" className="hero"><div className="hero-copy"><span className="kicker">Desenvolvedor Web <i/> UX Designer</span><h1>Transformo ideias em experiencias digitais <em>funcionais.</em></h1><p>Desenvolvedor web e estudante de Analise e Desenvolvimento de Sistemas, com interesse em UX, automacoes, inteligencia artificial e integracao de APIs.</p><div className="hero-actions"><a className="button" href="#projetos">Ver projetos <ArrowRight/></a><a className="button secondary" href="#contato">Entrar em contato</a><a className="icon-button" href="https://github.com/mariomoutinho" target="_blank" rel="noreferrer" aria-label="GitHub de Luiz Moutinho"><Github/></a></div></div><div className="hero-visual" aria-label="Areas de atuacao"><div className="code-window"><div className="window-bar"><i/><i/><i/><span>luiz.portfolio.ts</span></div><pre><code><span>const</span> trabalho = {'{'}{`\n`}  foco: <b>'pessoas'</b>,{`\n`}  meios: [<b>'codigo'</b>, <b>'UX'</b>],{`\n`}  metodo: <b>'aprender + construir'</b>{`\n`}{'}'}</code></pre></div><ul className="orbit-labels"><li>Front-end</li><li>UX / UI</li><li>IA</li><li>Automacao</li></ul></div><a className="scroll-cue" href="#sobre">Conheca meu trabalho <ChevronDown/></a></section>

    <section id="sobre" className="section split"><div><span className="section-index">01 / Sobre</span><h2>Entre a logica da solucao e a experiencia de quem usa.</h2></div><div className="about-copy"><p className="large">Gosto de entender o problema antes de escolher a ferramenta. Meu trabalho conecta desenvolvimento e UX para transformar ideias em prototipos claros, testaveis e uteis.</p><p>Sou estudante de Analise e Desenvolvimento de Sistemas na UNINTER. Tenho curiosidade por interfaces, automacoes, IA generativa e integracao de APIs, sempre com uma postura pratica: pesquisar, construir, validar e melhorar.</p><div className="traits"><span>Comunicacao clara</span><span>Curiosidade</span><span>Aprendizado continuo</span><span>Atitude pratica</span></div></div></section>

    <section id="projetos" className="section"><div className="section-heading"><div><span className="section-index">02 / Projetos</span><h2>Trabalhos em destaque</h2></div><p>Produtos, interfaces e experimentos que mostram diferentes maneiras de resolver problemas.</p></div><div className="project-grid">{projects.map(p=><ProjectCard key={p.id} project={p} onOpen={setSelected}/>)}</div></section>

    <section id="processo" className="section process-section"><div className="section-heading"><div><span className="section-index">03 / Processo</span><h2>UX e desenvolvimento no mesmo fluxo.</h2></div><p>Uma sequencia simples, que volta ao inicio sempre que um teste revela algo novo.</p></div><ol className="process-list">{process.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong>{i<process.length-1&&<ArrowRight/>}</li>)}</ol></section>

    <section id="competencias" className="section"><div className="section-heading"><div><span className="section-index">04 / Competencias</span><h2>Conhecimento aplicado, sem barras arbitrarias.</h2></div><p>Competencias reunidas a partir dos projetos do workspace e dos estudos em andamento.</p></div><div className="skills-grid">{skills.map(s=><article key={s.title}><Code2/><span>{s.note}</span><h3>{s.title}</h3><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>

    <section id="formacao" className="section split education"><div><span className="section-index">05 / Formacao</span><h2>Base academica e estudo continuo.</h2><article className="degree"><span>2025 - 2028</span><h3>Analise e Desenvolvimento de Sistemas</h3><p>Centro Universitario Internacional - UNINTER</p></article></div><div><h3 className="subheading">Trilhas de estudo</h3>{[['Desenvolvimento web','HTML, CSS, JavaScript, TypeScript, SASS, Angular 19 e Node.js.'],['Qualidade e UX','UX Design, Quality Assurance, plano de testes, bugs e testes de integracao.'],['IA e infraestrutura','Engenharia de Prompt, ChatGPT, IA generativa, Java e Google Cloud Compute Engine.']].map(([t,d])=><details key={t}><summary>{t}<ChevronDown/></summary><p>{d}</p></details>)}</div></section>

    <section className="section other"><div className="section-heading"><div><span className="section-index">06 / Exploracoes</span><h2>Outros projetos</h2></div></div><div className="other-grid">{otherProjects.map(p=><article key={p.name}><span>{p.label}</span><h3>{p.name}</h3><p>{p.summary}</p>{p.repo&&<a href={p.repo} target="_blank" rel="noreferrer" aria-label={`Codigo de ${p.name}`}><Github/> Codigo <ExternalLink/></a>}</article>)}</div></section>

    <section id="contato" className="contact"><span className="section-index">07 / Contato</span><h2>Tem uma ideia que precisa sair do papel?</h2><p>Estou aberto a conversar com recrutadores, empresas e pessoas interessadas em construir experiencias digitais com cuidado.</p><div className="contact-actions"><a className="button light" href="mailto:luizmariomoutinho1@gmail.com"><Mail/> Enviar e-mail</a><button className="button secondary-light" onClick={copyEmail}>{copied?<Check/>:<Copy/>}{copied?'E-mail copiado':'Copiar e-mail'}</button><a className="button secondary-light" href="https://wa.me/5581992579809" target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div><a className="contact-email" href="mailto:luizmariomoutinho1@gmail.com">luizmariomoutinho1@gmail.com</a></section>
  </main><footer><a className="monogram" href="#inicio">LM</a><p>Luiz Moutinho © {new Date().getFullYear()}</p><p>Construido com React, TypeScript e atencao aos detalhes.</p><a href="https://github.com/mariomoutinho/portfolio-luiz-moutinho" target="_blank" rel="noreferrer">Codigo do portfolio <ExternalLink/></a></footer>{selected&&<CaseDialog project={selected} onClose={()=>setSelected(null)}/>}</>
}
